#!/usr/bin/env bash

# USAGE:
#
#   ./ake package archlinux "$pkgdir"
#

package() {
  distribution=$1; prefix="$2"
  [[ "$prefix" == "" ]] && echo "ERROR: USAGE is ./ake package <distribution> <prefix>" && exit 1
  case "$distribution" in
    ubuntu ) lib="lib" ;;
    * ) lib="usr/lib" ;;
  esac

  mkdir -p "$prefix/usr/share/gutaur"
  mkdir -p "$prefix/$lib/systemd/system"
  mkdir -p "$prefix/usr/bin"
  cp -r bin libexec VERSION "$prefix/usr/share/gutaur"
  cp misc/systemd/* "$prefix/$lib/systemd/system"
  ln -s "/usr/share/gutaur/bin/gutaur" "$prefix/usr/bin"
}

case "$1" in
  p | package ) shift; package "$@" ;;
  b | build )
esac
