#!/usr/bin/env bash
#
# Summary: Generate a source-only tarball.
#
# Usage: gutaur source
#
# It invokes makepkg --source command, and generate a source-only tarball without downloaded sources.

set -e
(( $DEBUG >= 3 )) && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  app-sums
  makepkg --source "$@"
}

main "$@"
