#!/usr/bin/env bash
#
# Summary: Check upstream for new version
#
# Usage: gutaur check [version url regexp]
#

set -e
(( $DEBUG >= 3 )) && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  if [[ "$1" == "" ]]; then
    arg=$(app-cat)
    if [[ $arg == "" ]];then
      say "::SKIP:: $dir -- there is no _watch in PKGBUILD file"
    else
      gutaur-check $arg
    fi
  else
    gutaur-check "$@"
  fi
}

main "$@"
