#!/usr/bin/env bash
#
# Summary: Build the package
#
# Usage: gutaur build
#
# Invokes makepkg -sf

set -e
[ -n "$APP_DEBUG" ] && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  makepkg -sf "$@"
}

main "$@"
