#!/usr/bin/env bash
# fork from https://gist.github.com/pyropeter/556538
#
# Summary: Upload source tarball to AUR website.
#
# Usage: gutaur upload <tarball>
#
# Upload source tarball to https://aur.archlinux.org

set -e
[ -n "$APP_DEBUG" ] && set -x
source "$APP_ROOT/libexec/lib.sh"

[[ -z "$1" ]] && app-help --usage upload >&2 && exit 1

AUR_CONFIG=${AUR_CONFIG:-$HOME/.config/aurupload.conf}
declare -A categorys
categorys[daemons]=2
categorys[devel]=3
categorys[editors]=4
categorys[emulators]=5
categorys[games]=6
categorys[gnome]=7
categorys[i18n]=8
categorys[kde]=9
categorys[kernels]=19
categorys[lib]=10
categorys[modules]=11
categorys[multimedia]=12
categorys[network]=13
categorys[office]=14
categorys[science]=15
categorys[system]=16
categorys[x11]=17
categorys[xfce]=18

verbose=0
if [ "${1:-}" == "-v" ]; then
  verbose=1
  shift 1
fi

if [ $# -lt 1 ]; then
  echo "Usage: aurupload [category] <path to src-pkg>"
  echo "Valid categorys are: ${!categorys[*]}"
  echo "If pass is -, aurupload asks interactively."
  exit 1
fi

if [ $# -lt 2 ]; then
  category=1
  filename=$1
else
  category=${categorys[$1]:-errorerror}
  filename=$2
fi

if [ $category = "errorerror" ]; then
  echo "Invalid category"
  exit 2
fi

[[ -e "$AUR_CONFIG" ]] && source "$AUR_CONFIG"

if [[ $AUR_USERNAME == "" || $AUR_PASSWORD == "" ]]; then
  echo "You must provide username and password in ~/.config/aurupload.conf or AUR_USERNAME and AUR_PASSWORD environment variable" >&2
  exit 1
fi

echo "Logging in..."

response=`curl -sSi -F user=$AUR_USERNAME -F passwd=$AUR_PASSWORD -H 'Expect: ' https://aur.archlinux.org/login/`
sessid=`echo "$response" | awk '/^Set-Cookie: / {print $2}' | tr -d ';'`

if [ $verbose -gt 0 ]; then
  echo "$response"
fi

if [ -z "$sessid" ]; then
  echo "Login failed. Wrong username/password?" >&2
  exit 1
fi

echo "Done, sessionid is $sessid"

echo "Requesting upload token..."

response=`curl -sSi -H 'Expect: ' -b $sessid https://aur.archlinux.org/submit/`
token=`echo "$response" | grep 'input.type..hidden..name..token..value' | cut -d\" -f6`

if [ $verbose -gt 0 ]; then
  echo "$response"
fi

if [ -z "$token" ]; then
  echo "Could not get the token." >&2
  exit 1
fi

echo "Done, token is $token"

echo "Uploading file..."

response=`curl -sSi -H 'Expect: ' -F token="$token" -F pkgsubmit=1 -F category=$category -F pfile=@$filename -b $sessid https://aur.archlinux.org/submit/`
error=`echo "$response" | grep 'class="errorlist"' | sed 's/\s*<[^>]*>//g'`
package=`echo "$response" | awk '/^Location: / {print $2}'`

if [ $verbose -gt 0 ]; then
  echo "$response"
fi

if [ "$error" ]; then
  echo "Error: $error" >&2
  exit 1
else
  echo "Done, (new) package is https://aur.archlinux.org$package"
fi
