#!/usr/bin/env bash
#
# Summary: Clean all *.src.tar.gz *.pkg.tar.xz
#
# Usage: gutaur clean
#
# Clean all *.src.tar.gz *.pkg.tar.xz

set -e
(( $DEBUG >= 3 )) && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  rm -rf src pkg *.src.tar.gz *.pkg.tar.xz
}

main "$@"
