#!/usr/bin/env bash
#
# Summary: Build the package
#
# Usage: gutaur build
#
# Invokes makepkg -sf

set -e
(( $DEBUG >= 3 )) && set -x
source "$APP_ROOT/libexec/lib.sh"

main() {
  app-sums
  makepkg -sf "$@"
}

main "$@"
